article/urls.py
from django.urls import path

from . import views

app_name = "article"
urlpatterns = [
	path('new/', views.article_editor, name="new"),
	path("edit/<slug:pub_date>/<slug:article_name>/", views.article_edit_article, name="edit"),
	path('list/', views.ArticleList.as_view(), name="list"),
	path('', views.ArticleList.as_view(), name="list"),
	path("view/<slug:pub_date>/<slug:article_name>/", views.detail_view, name = "details"),
]

inscribe/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('markdownx/', include("markdownx.urls")),
    path("", include('article.urls')),
    path("article/", include('article.urls')),
    path("about/", TemplateView.as_view(template_name = "about.html"), name="about"),
    path("resume/", TemplateView.as_view(template_name = "resume.html"), name="resume"),
    path('accounts/', include('django.contrib.auth.urls')),
]

article/models.py
from django.db import models
from markdownx.models import MarkdownxField
import datetime 
from django.template.defaultfilters import slugify
from markdownx.utils import markdownify

from django.contrib.auth.models import User

# Create your models here.
class ArticleModel(models.Model):
    """
    Description: Model Description
    """
    title_text = models.CharField(max_length=1000, blank=False, null = False, default="")
    author_text = models.ForeignKey(User, on_delete=models.CASCADE)
    article_text = MarkdownxField()
    published_date = models.DateField(auto_now=True)
    slug_title_text = models.SlugField(editable=False, unique=True)

    @property
    def formatted_markdown(self):
        return markdownify(self.article_text)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug_title_text = slugify(self.title_text)
            self.published_date = datetime.datetime.now().date()

        super(ArticleModel, self).save(*args, **kwargs)


    class Meta:
        unique_together = ('title_text', 'author_text', 'published_date')
   

article/forms.py
from django.forms import ModelForm
from . import models

class ArticleForm(ModelForm):

	class Meta:
		model = models.ArticleModel
		fields = ["title_text", 'article_text']

article/views.py
from django.shortcuts import render, get_object_or_404, reverse
from . import forms
from django.http import HttpResponseRedirect

from .models import ArticleModel
from django.views import generic

from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def article_editor(request):
	if request.method == "POST":
		article_edit_form = forms.ArticleForm(request.POST)
		if article_edit_form.is_valid():
			article_object = article_edit_form.save(commit=False)
			article_object.author_text = request.user
			article_object.save()
			return HttpResponseRedirect(reverse('article:details', args=(article_object.published_date, article_object.slug_title_text)))
	article_edit_form = forms.ArticleForm(label_suffix="")
	print(article_edit_form)
	return render(request, 'article/new.html', {"form" : article_edit_form, 'new_article_button': False})

class ArticleList(generic.ListView):
	model = ArticleModel
	template_name = "article/list.html"

def detail_view(request, pub_date, article_name):
	article_object = get_object_or_404(ArticleModel, published_date = pub_date, slug_title_text = article_name)
	return render(request, "article/details.html", {'article_object': article_object})

def article_edit_article(request, pub_date, article_name):
	article_object = get_object_or_404(ArticleModel, published_date = pub_date, slug_title_text = article_name)
	if request.method == "POST":
		article_form = forms.ArticleForm(request.POST, instance=article_object)
		if article_form.is_valid():
			article_object_new = article_form.save()
			return HttpResponseRedirect(reverse('article:details', args=(article_object_new.published_date, article_object_new.slug_title_text)))
	article_form = forms.ArticleForm(instance = article_object)
	return render(request, "article/edit.html", { "form": article_form })

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
About
{% endblock %}

{% block content %}
	<div class="about_container">
		<div>
			<div class="profile_image_container">
				<img src="{% static 'media/images/profile.png' %}">
			</div>
			<p> I am Kartik Verma. I am a technology geek by passion and profession. I am an android developer, competitive programmer, deep learning enthusiast ...  And now trying to learn web programming.</p>
		</div>
	</div>
{% endblock %}

templates/article/article_form.html
<div class="create_article_container"> 
    <form method="POST">
        <button type="submit">Save</button>
        {% csrf_token %}
        {{ form }}
    </form>
    {{ form.media }}
</div>

templates/article/details.html
{% extends 'base.html' %}

{% block title %}
    Article - {{ article_object.title_text }}
{% endblock %}

{% block content %}
    {% if article_object %}
        <div class="article_details_container">
            <div class="top_details">
                <p class="pub_date">{{ article_object.published_date }}</p>
                <h1 class="title_text">{{ article_object.title_text }}</h1>
                {% if user.is_authenticated %}
                    {% if request.user.is_superuser or article.author_text == request.user %}
                        <a href="{% url 'article:edit' article_object.published_date article_object.slug_title_text %}"><i class="material-icons">edit</i></a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="article_text">{{ article_object.formatted_markdown | safe }}</div>
        </div>
    {% endif %}
{% endblock %}

templates/article/edit.html
{% extends 'base.html' %}

{% block title %}
	New Article
{% endblock %}

{% block content %}
	{% include 'article/article_form.html' %}
{% endblock %}

templates/article/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blogs {% endblock %}

{% block content %}

	<div class="article_list_container">
		{% if object_list %}
			<ul class="article_list_ul">
				{% for article in object_list %}
					<li class="article_item">
						<a href="{% url 'article:details' article.published_date article.slug_title_text %}">
							<img src="{% static 'media/images/temporary_image.png' %}">
							<div class="details">
								<div class="spanned">
									<span class="author_text"><span>By </span>{{ article.author_text }}</span>
									<span class="bullet">&bull;</span>
									<span class="published_date">{{ article.published_date }}</span>
								</div>
								<h2 class="title_text">{{ article.title_text }}</h2>
							</div>
						</a>
						<div class="float_icons">
							{% if user.is_authenticated %}
								{% if request.user.is_superuser or article.author_text == request.user %}
									<a href="{% url 'article:edit' article.published_date article.slug_title_text %}"><i class="material-icons">edit</i></a>
								{% endif %}
							{% endif %}
						</div>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<div class="no_data_found">
				<p>;-(<br />No Articles Yet </p>
			</div>
		{% endif %}
	</div>

{% endblock %}

<script type="text/javascript" src="{% static 'js/article.js' %}"></script>

templates/article/new.html
{% extends 'base.html' %}

{% block title %}
	New Article
{% endblock %}

{% block content %}
	{% include 'article/article_form.html' %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Passion+One|Viga|Open+Sans" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
</head>
<body>
	<nav>
		<div>
			<h1>Inscribe</h1>
			<div onclick="show_menu();" class="menu_image">
				<img src="{% static 'media/images/menu.png' %}">
			</div>
		</div>
		<ul id="menu_list">
			<li><a href="{% url 'article:list' %}">Blogs</a></li>
			<li><a href="{% url 'about' %}">About</a></li>
			<li><a href="#">Contact</a></li>
			<li class="resume_link"><a href="{% url 'resume' %}" target="_blank">Resume</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'logout' %}">Logout</a></li>
			{% endif %}
		</ul>
		{% if user.is_authenticated and new_article_button == None %}
		<div class="some-options">
			<ul>
				<li>
					<a href="{% url 'article:new' %}">
						<i class="material-icons image_icons">add</i><p>Add New Article</p>
					</a>
				</li>
			</ul>
		</div>
		{% endif %}
	</nav>
	<main>
		{% block content %}
		{% endblock %}
	</main>
	<footer>
		<hr>
		<p>All rights reserved &copy; Kartik Verma. 2019</p>
	</footer>
	<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
</body>
</html>

templates/markdownx/widget.html
<div class="markdownx row-custom">
    <div class="col1">
    {{ markdownx_editor }}
    </div>
    <div class="col1">
        <div class="markdownx-preview"></div>
    </div>
</div>